


export const images = [
    { id: "2", imageName: "2.jpg", tag: "technology", title:"Air Conditioner" },
    { id: "3", imageName: "3.jpg", tag: "technology", title:"Microphone" },
    { id: "4", imageName: "4.jpg", tag: "fashion", title:"Lady's Red Handbag" },
    { id: "5", imageName: "5.jpg", tag: "fashion", title:"Gent's Suit" },
    { id: "6", imageName: "6.jpg", tag: "technology", title:"Electric Blender" },
    { id: "7", imageName: "7.jpg", tag: "technology", title:"Electric Blender" },
    { id: "8", imageName: "8.jpg", tag: "fashion", title:"Gent's Jeans Top" },
    { id: "9", imageName: "9.jpg", tag: "fashion", title:"Gent's Cotton Top" },
    { id: "10", imageName: "10.jpg", tag: "technology", title:"Samsung A75" },
    { id: "11", imageName: "11.jpg", tag: "technology", title:"Electric Kettle" },
    { id: "12", imageName: "12.jpg", tag: "fashion", title:"Courtesy Heels" },
    { id: "13", imageName: "13.jpg", tag: "fashion", title:"Lady's White Heels" },
    { id: "14", imageName: "14.jpg", tag: "technology", title:"Modern Headset" },
    { id: "15", imageName: "15.jpg", tag: "fashion", title:"Lady's Red Heels" },
    { id: "16", imageName: "16.jpg", tag: "home", title:"Domestic Knives Set" },
    { id: "17", imageName: "17.jpg", tag: "fashion", title:"All Star Sneakers" },
    { id: "18", imageName: "18.jpg", tag: "fashion", title:"Gents Appealing Sneakers" },
    { id: "19", imageName: "19.jpg", tag: "fashion", title:"Super Sports Sneakers" },
    { id: "20", imageName: "20.jpg", tag: "technology", title:"Super Music Headkit" },
    { id: "21", imageName: "21.jpg", tag: "fashion", title:"Ladies' short wear" },
    { id: "22", imageName: "22.jpg", tag: "fashion", title:"Gent's Gray Cotton Sleeves" },
    { id: "23", imageName: "23.jpg", tag: "technology", title:"Music Headkit" },
    { id: "24", imageName: "24.jpg", tag: "home", title:"Modern Kettle" },
    { id: "24", imageName: "25.jpg", tag: "fashion", title:"American" },
    { id: "26", imageName: "26.jpg", tag: "fashion", title:"African Handbag" },
    { id: "27", imageName: "27.jpg", tag: "technology", title:"iPhone 13 Pro Max" },
    { id: "28", imageName: "28.png", tag: "home", title:"Recipe Tray" },
    { id: "29", imageName: "29.jpg", tag: "fashion", title:"Super Nike" },
    { id: "30", imageName: "30.jpg", tag: "fashion", title:"Golden Heels" },
    { id: "31", imageName: "31.jpg", tag: "home", title:"Kettle Set" },
    { id: "32", imageName: "32.jpg", tag: "fashion", title:"Fanthom Jacket" },
    { id: "33", imageName: "33.jpg", tag: "technology", title:"Virtual Reality Pro" },
  ];